const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const renderConfig = fs.readFileSync(path.resolve(__dirname, '../../render.yaml'), 'utf8');

function serviceBlock(name) {
  const marker = `    name: ${name}`;
  const start = renderConfig.indexOf(marker);
  assert.notEqual(start, -1, `missing ${name} service`);
  const next = renderConfig.indexOf('\n  - type:', start);
  return renderConfig.slice(start, next === -1 ? undefined : next);
}

test('Render uses process liveness for deploy health and keeps the exact browser origin contract', () => {
  const api = serviceBlock('maitri-inventory-api');
  assert.match(api, /\n    runtime: node\r?\n/);
  assert.match(api, /\n    plan: free\r?\n/);
  assert.match(api, /\n    healthCheckPath: \/health\r?\n/);
  assert.match(api, /key: CORS_ORIGIN\r?\n\s+value: https:\/\/maitri-inventory-web\.onrender\.com/);
});

test('Render serves the frontend as a static site with the exact API origin', () => {
  const web = serviceBlock('maitri-inventory-web');
  assert.match(web, /\n    runtime: static\r?\n/);
  assert.match(web, /\n    staticPublishPath: \.\/out\r?\n/);
  assert.match(web, /key: NEXT_PUBLIC_API_URL\r?\n\s+value: https:\/\/maitri-inventory-api\.onrender\.com/);
  assert.doesNotMatch(web, /startCommand|healthCheckPath|plan:/);
});

test('database credentials remain secret and JWT is generated by Render', () => {
  const api = serviceBlock('maitri-inventory-api');
  assert.match(api, /key: DATABASE_URL\r?\n\s+sync: false/);
  assert.match(api, /key: JWT_SECRET\r?\n\s+generateValue: true/);
  assert.doesNotMatch(api, /postgres(?:ql)?:\/\//i);
  assert.doesNotMatch(api, /key: (?:DATABASE_URL|JWT_SECRET)\r?\n\s+value:/);
});
